### Site Settings ###
title               : My KK Dashboard
description         : "The starting place on the web!"
baseurl             : ""                        # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : yousinix/portfolYOU       # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : yousinix/portfolYOU
open_new_tab        : true                      # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/blog.html
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Michal Ferber
  image             : https://michalferber.me/assets/img/profile.jpg
  github            : MichalAFerber
  stackoverflow     : ""
  twitter           : MichalAFerber
  youtube           : "@MichalAFerber"
  keybase           : MichalAFerber
  telegram          : MichalAFerber
  email             : michal@michalferber.me


### Exclude from processing ###
exclude:
  - vendor
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
