services:
  web:
    build: .
    container_name: start.mykk.us
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    ports:
      - "8050:3000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/usr/src/app/data
      - ./public/icons:/usr/src/app/public/icons
      - ./public/uploads:/usr/src/app/public/uploads